// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: helloworld.proto

package io.grpc.examples.helloworld;

public interface HelloReplyOrBuilder extends
    // @@protoc_insertion_point(interface_extends:helloworld.HelloReply)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>repeated string message = 1;</code>
   */
  java.util.List<java.lang.String>
      getMessageList();
  /**
   * <code>repeated string message = 1;</code>
   */
  int getMessageCount();
  /**
   * <code>repeated string message = 1;</code>
   */
  java.lang.String getMessage(int index);
  /**
   * <code>repeated string message = 1;</code>
   */
  com.google.protobuf.ByteString
      getMessageBytes(int index);
}
