// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: helloworld.proto

package io.grpc.examples.helloworld;

public final class HelloWorldProto {
  private HelloWorldProto() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_helloworld_ByeRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_helloworld_ByeRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_helloworld_ByeReply_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_helloworld_ByeReply_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_helloworld_HelloRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_helloworld_HelloRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_helloworld_HelloReply_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_helloworld_HelloReply_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\020helloworld.proto\022\nhelloworld\"+\n\nByeReq" +
      "uest\022\014\n\004name\030\001 \001(\t\022\017\n\007content\030\002 \001(\t\"%\n\010B" +
      "yeReply\022\014\n\004name\030\001 \001(\t\022\013\n\003msg\030\002 \001(\t\"C\n\014He" +
      "lloRequest\022\014\n\004name\030\001 \001(\t\022\017\n\007address\030\002 \001(" +
      "\t\022\024\n\014streetnumber\030\003 \001(\005\"\035\n\nHelloReply\022\017\n" +
      "\007message\030\001 \003(\t2\203\001\n\007Greeter\022>\n\010SayHello\022\030" +
      ".helloworld.HelloRequest\032\026.helloworld.He" +
      "lloReply\"\000\0228\n\006SayBye\022\026.helloworld.ByeReq" +
      "uest\032\024.helloworld.ByeReply\"\000B6\n\033io.grpc." +
      "examples.helloworldB\017HelloWorldProtoP\001\242\002",
      "\003HLWb\006proto3"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
        new com.google.protobuf.Descriptors.FileDescriptor.    InternalDescriptorAssigner() {
          public com.google.protobuf.ExtensionRegistry assignDescriptors(
              com.google.protobuf.Descriptors.FileDescriptor root) {
            descriptor = root;
            return null;
          }
        };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        }, assigner);
    internal_static_helloworld_ByeRequest_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_helloworld_ByeRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_helloworld_ByeRequest_descriptor,
        new java.lang.String[] { "Name", "Content", });
    internal_static_helloworld_ByeReply_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_helloworld_ByeReply_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_helloworld_ByeReply_descriptor,
        new java.lang.String[] { "Name", "Msg", });
    internal_static_helloworld_HelloRequest_descriptor =
      getDescriptor().getMessageTypes().get(2);
    internal_static_helloworld_HelloRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_helloworld_HelloRequest_descriptor,
        new java.lang.String[] { "Name", "Address", "Streetnumber", });
    internal_static_helloworld_HelloReply_descriptor =
      getDescriptor().getMessageTypes().get(3);
    internal_static_helloworld_HelloReply_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_helloworld_HelloReply_descriptor,
        new java.lang.String[] { "Message", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
