// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: helloworld.proto

package io.grpc.examples.helloworld;

public interface HelloRequestOrBuilder extends
    // @@protoc_insertion_point(interface_extends:helloworld.HelloRequest)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>string name = 1;</code>
   */
  java.lang.String getName();
  /**
   * <code>string name = 1;</code>
   */
  com.google.protobuf.ByteString
      getNameBytes();

  /**
   * <code>string address = 2;</code>
   */
  java.lang.String getAddress();
  /**
   * <code>string address = 2;</code>
   */
  com.google.protobuf.ByteString
      getAddressBytes();

  /**
   * <code>int32 streetnumber = 3;</code>
   */
  int getStreetnumber();
}
